version: '3.7'
services:
    flat-search:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flatsearch
        depends_on:
            - storage
        links:
            - storage:storage
        environment:
            DB_HOST: storage
            DB_NAME: flat-search
            DB_USER: flat-agent
            DB_PASSWORD: test-flat-agent
        volumes:
            - go-pkg:/go/pkg
            - go-cache:/.cache

    storage:
        container_name: flatsearch-storage
        image: mysql:8.0.19
        environment:
            MYSQL_ROOT_PASSWORD: test100500
            MYSQL_DATABASE: flat-search
            MYSQL_USER: flat-agent
            MYSQL_PASSWORD: test-flat-agent
        ports:
           - 3306:3306

volumes:
    go-cache:
    go-pkg:
